nexpsp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='base.html')),
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls')),
    path('blockchain/', include('blockchain.urls')),

]

customer/models.py
from logzero import logger
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin

from django.db.models.signals import post_save
from django.dispatch import receiver
from localflavor.us.models import USZipCodeField, USStateField
from django.conf import settings

from .dwolla import dwolla_create_user, dwolla_update_user, dwolla_get_url, DwollaClient


ASSET_CHOICES = [
    ('GAS', 'GAS'),
    ('NEO', 'NEO'),
    ('NEX', 'NEX'),
    ('RPX', 'RPX')
]

PURCHASE_STATUS = [
    ('awaiting_deposit', 'awaiting_deposit'),
    ('gas_received', 'gas_received'),
    ('pending', 'pending'),
    ('processed', 'processed'),
    ('failed', 'failed'),
    ('complete', 'complete')
]


class PSPUserManager(BaseUserManager):
    """
    PSPUSer manager is a custom user manager for customer.models.PSPUser
    """

    def create_user(self, email, first, last, address1, city, postal_code, state, ssn_lastfour, date_of_birth, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            first_name=first,
            last_name=last,
            address1=address1,
            city=city,
            postal_code=postal_code,
            state=state,
            ssn_lastfour=ssn_lastfour,
            date_of_birth=date_of_birth
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, address1, city, postal_code, state, ssn_lastfour, date_of_birth, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            first_name, last_name, address1, city, postal_code, state, ssn_lastfour, date_of_birth,
            password=password,
        )

        user.is_admin = True
        user.save(using=self._db)
        return user


class PSPUser(AbstractBaseUser, PermissionsMixin):
    """
    PSP User is the model that represents any user on the website, whether admins or consumers. It inherits/conforms
    to the normal django user conventions

    """
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )

    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now=True)

    dwolla_url = models.URLField(blank=True, null=True)

    customer_type = models.CharField(max_length=32, default='personal')

    address1 = models.CharField(max_length=50)
    address2 = models.CharField(max_length=50, blank=True, null=True)
    city = models.CharField(max_length=128)
    postal_code = USZipCodeField()
    state = USStateField()
    ssn_lastfour = models.CharField(max_length=4)
    date_of_birth = models.DateField()

    is_seller = models.BooleanField(default=False)

    objects = PSPUserManager()

    pending_deposit = models.ForeignKey(
        'customer.Deposit', blank=True, null=True, on_delete=models.SET_NULL)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'address1', 'city',
                       'postal_code', 'state', 'ssn_lastfour', 'date_of_birth']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        """
        Is this user a staff user?
        Returns:
            bool
        """
        return self.is_admin

    @property
    def dwolla_id(self):
        """
        Retrieve the dwolla based id for this user
        Returns:
            str
        """
        if self.dwolla_url:
            return self.dwolla_url.split('/')[-1]
        return None

    def __str__(self):
        """
        return the user's email address

        Returns:
            str
        """
        return self.email

    def get_full_name(self):
        """
        returs full name of the user

        Returns:
            str
        """
        return '%s %s ' % (self.first_name, self.last_name)

    def get_short_name(self):
        """
        Get users first name
        Returns:
            str
        """
        return self.first_name

    def to_json(self):
        """
        output this user as a json object. The format is determined by the needs
        of the dwolla api

        Returns:
            dict
        """
        datetostr = self.date_of_birth.strftime('%Y-%m-%d')

        return {
            'email': self.email,
            'firstName': self.first_name,
            'lastName': self.last_name,
            'type': self.customer_type,
            'address1': self.address1,
            'city': self.city,
            'state': self.state,
            'postalCode': self.postal_code,
            'dateOfBirth': datetostr,
            'ssn': self.ssn_lastfour
        }

    def to_update_json(self):
        """
        output of the user as json needed for dwolla to update a user
        Returns:
            dict
        """
        return {
            'email': self.email,
            'firstName': self.first_name,
            'lastName': self.last_name,
        }


@receiver(post_save, sender=PSPUser)
def on_pspuser_saved(sender, instance, created, **kwargs):
    """
    When a PSP user is saved, we check to see if they are associatde with the dwolla system ( dwolla_url )
    if not, we will create a dwolla user

    Args:
        sender (customer.models.PSPUser): the model class that sends this event
        instance (customer.models.PSPUser): the instance of the model associated with this event
        created (bool): whether this instance has just been created
        **kwargs:

    """
    if instance.dwolla_url is None:

        dwolla_sync_result = dwolla_create_user(instance)
    else:
        dwolla_sync_result = dwolla_update_user(instance)

    logger.info("dwolla sync result: %s " % dwolla_sync_result)


class ReceiveableAccount(models.Model):
    """
    This is a model used to represent the main PSP user and associate them with their main
    bank account in dwolla

    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)

    account_id = models.CharField(max_length=128)

    def __str__(self):
        return 'Receivable Account for %s ' % self.user.last_name

    @property
    def customer_url(self):
        """
        The url for the receivable account customer dwolla account
        Returns:
            str
        """
        return self.user.dwolla_url

    @property
    def funding_url(self):
        """
        The url for the receivable account customer funding dwolla account

        Returns:
            str
        """
        return '%s%s' % (DwollaClient.instance().funding_source_url, self.account_id)

    @staticmethod
    def Default():
        """
        There should only be one, so this is kind of a singleton for retrieving it
        Returns:
            customer.models.ReceivableAccount
        """
        try:
            return ReceiveableAccount.objects.first()
        except Exception as e:
            pass
        return None


class Purchase(models.Model):
    """
    A Purchase represents when a user sends fiat to the ReceivableAccount
    """
    asset = models.CharField(choices=ASSET_CHOICES,
                             default='GAS', max_length=3)
    amount = models.FloatField(default=1.00)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)

    sender_account_id = models.CharField(max_length=128)

    receiver_account_id = models.CharField(max_length=128)

    neo_address = models.CharField(max_length=34)

    gas_price = models.FloatField()

    fee = models.FloatField(default=.05)

    total_gas = models.FloatField()
    total_fee = models.FloatField()

    total = models.FloatField()

    status = models.CharField(
        max_length=32, choices=PURCHASE_STATUS, default='pending')

    transfer_url = models.CharField(max_length=128)

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    failure_reason = models.CharField(max_length=1024, blank=True, null=True)

    blockchain_transfer = models.OneToOneField(
        'blockchain.BlockchainTransfer', blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date_created', ]


class Deposit(models.Model):
    """
    A deposit is for persisting when a user deposits crypto into the system in exchange for fiat
    """

    amount = models.FloatField(default=1.00, blank=True, null=True)

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.DO_NOTHING)

    sender_account_id = models.CharField(max_length=128)

    receiver_account_id = models.CharField(max_length=128)

    neo_sender_address = models.CharField(max_length=34, blank=True, null=True)

    asset = models.CharField(choices=ASSET_CHOICES,
                             default='GAS', max_length=3)
    gas_price = models.FloatField(blank=True, null=True)
    fee = models.FloatField(default=.05)
    total_gas = models.FloatField(blank=True, null=True)

customer/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from customer.models import PSPUser, Purchase, Deposit
from neo.Core.Helper import Helper
from neocore.Cryptography.Crypto import Crypto
from localflavor.us.us_states import STATE_CHOICES
from localflavor.us.forms import USStateField
from django.forms import ValidationError


class PSPUserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = PSPUser
        fields = ('email', 'first_name', 'last_name', 'address1', 'city',
                  'state', 'postal_code', 'ssn_lastfour', 'date_of_birth',)

    def __init__(self, *args, **kwargs):
        super(PSPUserCreationForm, self).__init__(*args, **kwargs)

        choices = list(STATE_CHOICES)
        choices[0] = ('', 'Select a State')
        self.fields['state'] = USStateField(
            widget=forms.Select(choices=choices))
        self.fields['date_of_birth'].widget.attrs = {
            'placeholder': 'Date of birth: YYYY-MM-DD'}

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class PSPUserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = PSPUser
        fields = ('email', 'first_name', 'last_name', 'address1', 'city',
                  'state', 'postal_code', 'ssn_lastfour', 'date_of_birth',)

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class PSPProfileForm(forms.ModelForm):
    """A form for users to update their profiles.
    """
    use_required_attribute = True
    required_css_class = 'required'

    class Meta:
        model = PSPUser
        fields = ('email', 'first_name', 'last_name', 'address1', 'city',
                  'state', 'postal_code', 'ssn_lastfour', 'date_of_birth',)


class BankAccountForm(forms.Form):

    pass


class PurchaseForm(forms.ModelForm):

    class Meta:
        model = Purchase
        fields = ['neo_address', 'amount', 'sender_account_id', ]

    def __init__(self, *args, **kwargs):
        accounts = None

        if 'accounts' in kwargs:
            accounts = kwargs.pop('accounts')

        super(PurchaseForm, self).__init__(*args, **kwargs)

        if accounts:
            choices = []
            for acct in accounts:
                choices.append((acct['id'], acct['name']))
            self.fields['sender_account_id'] = forms.ChoiceField(
                choices=choices, label='Bank Account')

        self.fields['neo_address'].widget.attrs = {
            'placeholder': 'Axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}

    def clean_neo_address(self):

        addr = self.cleaned_data['neo_address']

        try:
            shash = Helper.AddrStrToScriptHash(addr)
            address_output = Crypto.ToAddress(shash)

            assert address_output == addr

        except Exception as e:

            raise ValidationError("Invalid NEO Blockchain Address")

        return self.cleaned_data['neo_address']

    def clean_amount(self):
        amt = self.cleaned_data['amount']
        if amt <= 0:
            raise ValidationError('Must purchase more than 0 amount')
        return amt


class DepositForm(forms.ModelForm):

    deposit_wallet = None

    class Meta:
        model = Deposit
        fields = ['amount', 'receiver_account_id', ]

    def __init__(self, *args, **kwargs):
        accounts = None
        self.deposit_wallet = None
        if 'accounts' in kwargs:
            accounts = kwargs.pop('accounts')
        if 'deposit_wallet' in kwargs:
            self.deposit_wallet = kwargs.pop('deposit_wallet')

        super(DepositForm, self).__init__(*args, **kwargs)

        if accounts:
            choices = []
            for acct in accounts:
                choices.append((acct['id'], acct['name']))
            self.fields['receiver_account_id'] = forms.ChoiceField(
                choices=choices, label='Deposit To Bank Account:')


class CancelDepositForm(forms.Form):

    deposit_id = forms.IntegerField()

templates/deposit/awaiting_gas.html
   <div class="row justify-content-between">
                <div class="col-sm-12">
                    <div class="alert alert-warning" id="transaction-alert"><strong>[STATUS]</strong> {% ifequal deposit.status 'pending' %}awaiting deposit{% else %}{{ deposit.status }}{% endifequal %}</div>

                    <p>Once we have received your GAS deposit, your fiat will be credited to:</p>

                    <div class="form-group">
                        <input id="id_receiver_bank_account_id"  class="form-control" type="text" readonly value="{{ deposit.receiver_account.name }} at {{ deposit.receiver_account.bankName }} ({{ deposit.receiver_account.bankAccountType }})">
                    </div>

                    <hr/>

                    <p>Complete this deposit with the NEX extension</p>
                    <button type="button" class="btn btn-primary btn-block" id="id_open_in_nex">Open NEX extension</button>
                    <hr/>
<!--
                    <p>Alternatively, you may send the transaction from another wallet by using the following transaction details:</p>
                    <pre>
{
    toAddr: "{{ deposit_wallet.address }}",
    assetId: "602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7",
    transactionAttributes: [
        {
            usage: 243,
            data: "{{ deposit.invoice_id }}"
        }
    ]
}
                    </pre>
-->
                </div>
                <div class="col-sm-12">
                    <h5>Sale Estimator:</h5>

                    <div class="form-group col-sm-12">
                        <label for="id_amount">Amount</label>
                        <input type="number" name="amount" value="{{ deposit.amount }}" id="id_amount" placeholder="Amount" title="" class="form-control" step="any">
                    </div>
                </div>

                <div class="col-sm-12 total-container">
                    <div class="row no-gutters">
                        <div class="col-sm-4 total-losenge total-losenge-left">
                            <p class="text-center total-label">Initial Price</p>
                            <p id="id_gas_total"  class="text-center total-amount total-important">{{ price_GAS|floatformat:2 }}</p>
                        </div>
                        <div class="col-sm-4 total-losenge total-losenge-middle">
                            <p class="text-center total-label">Our 5% fee</p>
                            <p id="id_fee_total"  class="text-center total-amount total-important"></p>
                        </div>

                        <div class="col-sm-4 total-losenge total-losenge-right">
                            <p class="text-center total-label total-important">You will recieve</p>
                            <p id="id_total" class="text-center total-amount total-important"></p>
                        </div>
                    </div>
                </div>
            </div>

            <form method="post" action="{% url 'deposit-crypto-cancel' %}">
                {% csrf_token %}
                <input type="hidden" name="deposit_id" id="id_deposit_id" value="{{ deposit.id }}"/>
                <button type="submit" class="btn btn-secondary">Cancel deposit</button>
            </form>

templates/deposit/deposit_complete.html
<div class="row">
                <div class="col-sm-7">
                    <div class="alert alert-success">
                        Deposit to <strong>{{ deposit.receiver_account.name }}</strong> for the amount of <strong>${{ deposit.total|floatformat:2 }}</strong> is complete!
                    </div>
                </div>
            </div>

            <div class="row justify-content-between">

                <div class="col-sm-7">

                    <div class="form-group">
                        <label for="id_ach_transfer_id">Bank Tranfer Id</label>
                        <input id="id_receiver_bank_account_id"  class="form-control" type="text" readonly value="{{ deposit.transfer_id}}">
                    </div>

                    <p>Below are the details of the transaction received:</p>
                    <pre class="tx-json">
{{ deposit.blockchain_transfer.tx_json }}
                    </pre>
                </div>

                <div class="col-sm-4">


                    <div class="form-group">
                        <label for="id_transaction_id">Transaction ID</label>
                        <input type="text" name="transaction_id" readonly value="{{ deposit.blockchain_transfer.transaction_id }}" id="id_transaction_id" placeholder="TransactionId" title="" class="form-control" step="any">
                    </div>

                    <div class="form-group">
                        <label for="id_amount">Amount GAS Received</label>
                        <input type="number" name="amount" readonly value="{{ deposit.amount }}" id="id_amount" placeholder="Amount" title="" class="form-control" step="any">
                    </div>
                    <div class="form-group">
                        <label for="id_gas_total">Total Gas @ ${{ deposit.gas_price|floatformat:2 }}</label>
                        <input id="id_gas_total"  class="form-control" type="number" readonly value="{{ deposit.total_gas|floatformat:2 }}">
                    </div>
                    <div class="form-group">
                        <label for="id_fee_total">Total Fee <strong>5%</strong></label>
                        <input id="id_fee_total"  class="form-control" type="number" readonly value="{{ deposit.total_fee }}">
                    </div>

                    <div class="form-group">
                        <label for="id_total">Total Payout</label>
                        <input id="id_total" class="form-control" type="number" readonly value="{{ deposit.total }}">
                    </div>
                </div>



            </div>

templates/deposit/deposit_pending.html
            <div class="row justify-content-between">
                <div class="col-sm-7">
                    <div class="alert alert-warning"><strong>[STATUS]</strong> {% ifequal deposit.status 'pending' %}awaiting deposit{% else %}{{ deposit.status }}{% endifequal %}</div>

                    <p>Once we have received your deposit, all proceeds will be deposited to the following account:</p>

                    <div class="form-group">
                        <input id="id_receiver_bank_account_id"  class="form-control" type="text" readonly value="{{ deposit.receiver_account.name }} at {{ deposit.receiver_account.bankName }} ({{ deposit.receiver_account.bankAccountType }})">
                    </div>

                    <hr/>

                    <p>Use the following button to complete this deposit via the NEX Extension</p>
                    <button type="button" class="btn btn-lg btn-primary" id="id_open_in_nex">Initiate Deposit via NEX Extension</button>
                    <hr/>

                    <p>Alternatively, you may send the transaction from another wallet by using the following details:</p>
                    <pre>
{
    to_addr: "{{ deposit_wallet.address }}",
    transactionAttributes: [
        {
            usage: 243,
            data: "{{ deposit.invoice_id }}"
        }
    ]
}
                    </pre>
                </div>
                <div class="col-sm-4">
                    <h5>Sale Estimator:</h5>

                    <div class="form-group">
                        <label for="id_amount">Amount</label>
                        <input type="number" name="amount" value="{{ deposit.amount }}" id="id_amount" placeholder="Amount" title="" class="form-control" step="any">
                    </div>
                    <div class="form-group">
                        <label for="id_gas_total">Total Gas Price @ ${{ gas_price|floatformat:2 }}</label>
                        <input id="id_gas_total"  class="form-control" type="number" readonly value="{{ gas_price|floatformat:2 }}">
                    </div>
                    <div class="form-group">
                        <label for="id_fee_total">Total Fee <strong>5%</strong></label>
                        <input id="id_fee_total"  class="form-control" type="number" readonly value="">
                    </div>

                    <div class="form-group">
                        <label for="id_total">Estimated Payout</label>
                        <input id="id_total" class="form-control" type="number" readonly value="">
                    </div>
                </div>
            </div>

            <form method="post" action="{% url 'deposit-crypto-cancel' %}">
                {% csrf_token %}
                <input type="hidden" name="deposit_id" id="id_deposit_id" value="{{ deposit.id }}"/>
                <button type="submit" class="btn btn-danger btn-lg">Cancel deposit</button>
            </form>

templates/deposit/failed.html
        <div class="row">

            <div class="col-sm-12">
                <h4>Transfer failed.</h4>
            </div>
        </div>

templates/deposit/gas_received.html
            <div class="row">
                <div class="col-sm-7">
                    <div class="alert alert-success">
                        Your gas has been received!
                    </div>
                </div>
            </div>

            <div class="row justify-content-between">

                <div class="col-sm-7">

                    <div class="form-group">
                        <label for="id_receiver_bank_account_id">A deposit of USD to the following account is being prepared.</label>
                        <input id="id_receiver_bank_account_id"  class="form-control" type="text" readonly value="{{ deposit.receiver_account.name }} at {{ deposit.receiver_account.bankName }} ({{ deposit.receiver_account.bankAccountType }})">
                    </div>

                    <p>Below are the details of the transaction received:</p>
                    <pre class="tx-json">
{{ deposit.blockchain_transfer.tx_json }}
                    </pre>
                </div>

                <div class="col-sm-4">


                    <div class="form-group">
                        <label for="id_transaction_id">Transaction ID</label>
                        <input type="text" name="transaction_id" readonly value="{{ deposit.blockchain_transfer.transaction_id }}" id="id_transaction_id" placeholder="TransactionId" title="" class="form-control" step="any">
                    </div>

                    <div class="form-group">
                        <label for="id_amount">Amount GAS Received</label>
                        <input type="number" name="amount" readonly value="{{ deposit.amount }}" id="id_amount" placeholder="Amount" title="" class="form-control" step="any">
                    </div>
                    <div class="form-group">
                        <label for="id_gas_total">Total Gas @ ${{ deposit.gas_price|floatformat:2 }}</label>
                        <input id="id_gas_total"  class="form-control" type="number" readonly value="{{ deposit.total_gas|floatformat:2 }}">
                    </div>
                    <div class="form-group">
                        <label for="id_fee_total">Total Fee <strong>5%</strong></label>
                        <input id="id_fee_total"  class="form-control" type="number" readonly value="{{ deposit.total_fee }}">
                    </div>

                    <div class="form-group">
                        <label for="id_total">Total Payout</label>
                        <input id="id_total" class="form-control" type="number" readonly value="{{ deposit.total }}">
                    </div>
                </div>



            </div>

templates/deposit/pending_bank_transfer.html
            <div class="row">
                <div class="col-sm-7">
                    <div class="alert alert-success">
                        A transfer to your bank account <strong>{{ deposit.receiver_account.name }}</strong> for the amount of <strong>${{ deposit.total|floatformat:2 }}</strong> has been initiated.  It is waiting for ACH process to finish.
                    </div>
                </div>
            </div>

            <div class="row justify-content-between">

                <div class="col-sm-7">

                    <div class="form-group">
                        <label for="id_ach_transfer_id">Bank Tranfer Id</label>
                        <input id="id_receiver_bank_account_id"  class="form-control" type="text" readonly value="{{ deposit.transfer_id}}">
                    </div>

                    <p>Below are the details of the transaction received:</p>
                    <pre class="tx-json">
{{ deposit.blockchain_transfer.tx_json }}
                    </pre>
                </div>

                <div class="col-sm-4">


                    <div class="form-group">
                        <label for="id_transaction_id">Transaction ID</label>
                        <input type="text" name="transaction_id" readonly value="{{ deposit.blockchain_transfer.transaction_id }}" id="id_transaction_id" placeholder="TransactionId" title="" class="form-control" step="any">
                    </div>

                    <div class="form-group">
                        <label for="id_amount">Amount GAS Received</label>
                        <input type="number" name="amount" readonly value="{{ deposit.amount }}" id="id_amount" placeholder="Amount" title="" class="form-control" step="any">
                    </div>
                    <div class="form-group">
                        <label for="id_gas_total">Total Gas @ ${{ deposit.gas_price|floatformat:2 }}</label>
                        <input id="id_gas_total"  class="form-control" type="number" readonly value="{{ deposit.total_gas|floatformat:2 }}">
                    </div>
                    <div class="form-group">
                        <label for="id_fee_total">Total Fee <strong>5%</strong></label>
                        <input id="id_fee_total"  class="form-control" type="number" readonly value="{{ deposit.total_fee }}">
                    </div>

                    <div class="form-group">
                        <label for="id_total">Total Payout</label>
                        <input id="id_total" class="form-control" type="number" readonly value="{{ deposit.total }}">
                    </div>
                </div>



            </div>